// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: notification.proto

package Notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNotificationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Deadline      string                 `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	TaskId        string                 `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	MaterialsId   string                 `protobuf:"bytes,5,opt,name=materials_id,json=materialsId,proto3" json:"materials_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationReq) Reset() {
	*x = CreateNotificationReq{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationReq) ProtoMessage() {}

func (x *CreateNotificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationReq.ProtoReflect.Descriptor instead.
func (*CreateNotificationReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNotificationReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateNotificationReq) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

func (x *CreateNotificationReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateNotificationReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateNotificationReq) GetMaterialsId() string {
	if x != nil {
		return x.MaterialsId
	}
	return ""
}

func (x *CreateNotificationReq) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type CreateNotificationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNotificationRes) Reset() {
	*x = CreateNotificationRes{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNotificationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNotificationRes) ProtoMessage() {}

func (x *CreateNotificationRes) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNotificationRes.ProtoReflect.Descriptor instead.
func (*CreateNotificationRes) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

type RemoveNotioficationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNotioficationReq) Reset() {
	*x = RemoveNotioficationReq{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNotioficationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNotioficationReq) ProtoMessage() {}

func (x *RemoveNotioficationReq) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNotioficationReq.ProtoReflect.Descriptor instead.
func (*RemoveNotioficationReq) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveNotioficationReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveNotioficationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNotioficationRes) Reset() {
	*x = RemoveNotioficationRes{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNotioficationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNotioficationRes) ProtoMessage() {}

func (x *RemoveNotioficationRes) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNotioficationRes.ProtoReflect.Descriptor instead.
func (*RemoveNotioficationRes) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\"\xbf\x01\n" +
	"\x15CreateNotificationReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1a\n" +
	"\bdeadline\x18\x02 \x01(\tR\bdeadline\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12!\n" +
	"\fmaterials_id\x18\x05 \x01(\tR\vmaterialsId\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\"\x17\n" +
	"\x15CreateNotificationRes\"(\n" +
	"\x16RemoveNotioficationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x18\n" +
	"\x16RemoveNotioficationRes2\xcf\x01\n" +
	"\fNotification\x12\\\n" +
	"\x10AddNotiofication\x12#.notification.CreateNotificationReq\x1a#.notification.CreateNotificationRes\x12a\n" +
	"\x13RemoveNotiofication\x12$.notification.RemoveNotioficationReq\x1a$.notification.RemoveNotioficationResB5Z3github.com/DEEBBLUE/StudyContracts/api/Notificationb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_notification_proto_goTypes = []any{
	(*CreateNotificationReq)(nil),  // 0: notification.CreateNotificationReq
	(*CreateNotificationRes)(nil),  // 1: notification.CreateNotificationRes
	(*RemoveNotioficationReq)(nil), // 2: notification.RemoveNotioficationReq
	(*RemoveNotioficationRes)(nil), // 3: notification.RemoveNotioficationRes
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: notification.Notification.AddNotiofication:input_type -> notification.CreateNotificationReq
	2, // 1: notification.Notification.RemoveNotiofication:input_type -> notification.RemoveNotioficationReq
	1, // 2: notification.Notification.AddNotiofication:output_type -> notification.CreateNotificationRes
	3, // 3: notification.Notification.RemoveNotiofication:output_type -> notification.RemoveNotioficationRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
