// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: notification.proto

package Notification

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Notification_AddNotioficationForGroup_FullMethodName    = "/notification.Notification/AddNotioficationForGroup"
	Notification_RemoveNotioficationForGroup_FullMethodName = "/notification.Notification/RemoveNotioficationForGroup"
)

// NotificationClient is the client API for Notification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationClient interface {
	AddNotioficationForGroup(ctx context.Context, in *CreateNotificationForGroupReq, opts ...grpc.CallOption) (*CreateNotificationRes, error)
	RemoveNotioficationForGroup(ctx context.Context, in *RemoveNotioficationForGroupReq, opts ...grpc.CallOption) (*RemoveNotioficationRes, error)
}

type notificationClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationClient(cc grpc.ClientConnInterface) NotificationClient {
	return &notificationClient{cc}
}

func (c *notificationClient) AddNotioficationForGroup(ctx context.Context, in *CreateNotificationForGroupReq, opts ...grpc.CallOption) (*CreateNotificationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNotificationRes)
	err := c.cc.Invoke(ctx, Notification_AddNotioficationForGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationClient) RemoveNotioficationForGroup(ctx context.Context, in *RemoveNotioficationForGroupReq, opts ...grpc.CallOption) (*RemoveNotioficationRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNotioficationRes)
	err := c.cc.Invoke(ctx, Notification_RemoveNotioficationForGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServer is the server API for Notification service.
// All implementations must embed UnimplementedNotificationServer
// for forward compatibility.
type NotificationServer interface {
	AddNotioficationForGroup(context.Context, *CreateNotificationForGroupReq) (*CreateNotificationRes, error)
	RemoveNotioficationForGroup(context.Context, *RemoveNotioficationForGroupReq) (*RemoveNotioficationRes, error)
	mustEmbedUnimplementedNotificationServer()
}

// UnimplementedNotificationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServer struct{}

func (UnimplementedNotificationServer) AddNotioficationForGroup(context.Context, *CreateNotificationForGroupReq) (*CreateNotificationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNotioficationForGroup not implemented")
}
func (UnimplementedNotificationServer) RemoveNotioficationForGroup(context.Context, *RemoveNotioficationForGroupReq) (*RemoveNotioficationRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNotioficationForGroup not implemented")
}
func (UnimplementedNotificationServer) mustEmbedUnimplementedNotificationServer() {}
func (UnimplementedNotificationServer) testEmbeddedByValue()                      {}

// UnsafeNotificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServer will
// result in compilation errors.
type UnsafeNotificationServer interface {
	mustEmbedUnimplementedNotificationServer()
}

func RegisterNotificationServer(s grpc.ServiceRegistrar, srv NotificationServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Notification_ServiceDesc, srv)
}

func _Notification_AddNotioficationForGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationForGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).AddNotioficationForGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_AddNotioficationForGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).AddNotioficationForGroup(ctx, req.(*CreateNotificationForGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Notification_RemoveNotioficationForGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNotioficationForGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServer).RemoveNotioficationForGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Notification_RemoveNotioficationForGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServer).RemoveNotioficationForGroup(ctx, req.(*RemoveNotioficationForGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Notification_ServiceDesc is the grpc.ServiceDesc for Notification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Notification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.Notification",
	HandlerType: (*NotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNotioficationForGroup",
			Handler:    _Notification_AddNotioficationForGroup_Handler,
		},
		{
			MethodName: "RemoveNotioficationForGroup",
			Handler:    _Notification_RemoveNotioficationForGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
