// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: sso.proto

package SSO

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentsId    int32                  `protobuf:"varint,1,opt,name=students_id,json=studentsId,proto3" json:"students_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetStudentsId() int32 {
	if x != nil {
		return x.StudentsId
	}
	return 0
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentsId    int32                  `protobuf:"varint,1,opt,name=students_id,json=studentsId,proto3" json:"students_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{1}
}

func (x *UserId) GetStudentsId() int32 {
	if x != nil {
		return x.StudentsId
	}
	return 0
}

type Responce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Responce) Reset() {
	*x = Responce{}
	mi := &file_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Responce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Responce) ProtoMessage() {}

func (x *Responce) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Responce.ProtoReflect.Descriptor instead.
func (*Responce) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{2}
}

func (x *Responce) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type WhoImeRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoImeRes) Reset() {
	*x = WhoImeRes{}
	mi := &file_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoImeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoImeRes) ProtoMessage() {}

func (x *WhoImeRes) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoImeRes.ProtoReflect.Descriptor instead.
func (*WhoImeRes) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{3}
}

func (x *WhoImeRes) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ValidationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentsId    int32                  `protobuf:"varint,1,opt,name=students_id,json=studentsId,proto3" json:"students_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationRes) Reset() {
	*x = ValidationRes{}
	mi := &file_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationRes) ProtoMessage() {}

func (x *ValidationRes) ProtoReflect() protoreflect.Message {
	mi := &file_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationRes.ProtoReflect.Descriptor instead.
func (*ValidationRes) Descriptor() ([]byte, []int) {
	return file_sso_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationRes) GetStudentsId() int32 {
	if x != nil {
		return x.StudentsId
	}
	return 0
}

func (x *ValidationRes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_sso_proto protoreflect.FileDescriptor

const file_sso_proto_rawDesc = "" +
	"\n" +
	"\tsso.proto\x12\x03sso\"W\n" +
	"\x04User\x12\x1f\n" +
	"\vstudents_id\x18\x01 \x01(\x05R\n" +
	"studentsId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\")\n" +
	"\x06UserId\x12\x1f\n" +
	"\vstudents_id\x18\x01 \x01(\x05R\n" +
	"studentsId\"\"\n" +
	"\bResponce\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x1f\n" +
	"\tWhoImeRes\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"L\n" +
	"\rValidationRes\x12\x1f\n" +
	"\vstudents_id\x18\x01 \x01(\x05R\n" +
	"studentsId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2\xd7\x01\n" +
	"\x03SSO\x12&\n" +
	"\n" +
	"CreateUser\x12\t.sso.User\x1a\r.sso.Responce\x12&\n" +
	"\n" +
	"UpdateUser\x12\t.sso.User\x1a\r.sso.Responce\x12(\n" +
	"\n" +
	"DeleteUser\x12\v.sso.UserId\x1a\r.sso.Responce\x12%\n" +
	"\x06WhoIme\x12\v.sso.UserId\x1a\x0e.sso.WhoImeRes\x12/\n" +
	"\n" +
	"Validation\x12\x12.sso.ValidationRes\x1a\r.sso.ResponceB,Z*github.com/DEEBBLUE/StudyContracts/api/SSOb\x06proto3"

var (
	file_sso_proto_rawDescOnce sync.Once
	file_sso_proto_rawDescData []byte
)

func file_sso_proto_rawDescGZIP() []byte {
	file_sso_proto_rawDescOnce.Do(func() {
		file_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_proto_rawDesc), len(file_sso_proto_rawDesc)))
	})
	return file_sso_proto_rawDescData
}

var file_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sso_proto_goTypes = []any{
	(*User)(nil),          // 0: sso.User
	(*UserId)(nil),        // 1: sso.UserId
	(*Responce)(nil),      // 2: sso.Responce
	(*WhoImeRes)(nil),     // 3: sso.WhoImeRes
	(*ValidationRes)(nil), // 4: sso.ValidationRes
}
var file_sso_proto_depIdxs = []int32{
	0, // 0: sso.SSO.CreateUser:input_type -> sso.User
	0, // 1: sso.SSO.UpdateUser:input_type -> sso.User
	1, // 2: sso.SSO.DeleteUser:input_type -> sso.UserId
	1, // 3: sso.SSO.WhoIme:input_type -> sso.UserId
	4, // 4: sso.SSO.Validation:input_type -> sso.ValidationRes
	2, // 5: sso.SSO.CreateUser:output_type -> sso.Responce
	2, // 6: sso.SSO.UpdateUser:output_type -> sso.Responce
	2, // 7: sso.SSO.DeleteUser:output_type -> sso.Responce
	3, // 8: sso.SSO.WhoIme:output_type -> sso.WhoImeRes
	2, // 9: sso.SSO.Validation:output_type -> sso.Responce
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sso_proto_init() }
func file_sso_proto_init() {
	if File_sso_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_proto_rawDesc), len(file_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_proto_goTypes,
		DependencyIndexes: file_sso_proto_depIdxs,
		MessageInfos:      file_sso_proto_msgTypes,
	}.Build()
	File_sso_proto = out.File
	file_sso_proto_goTypes = nil
	file_sso_proto_depIdxs = nil
}
